branch-defaults:
  main:
    environment: graphql-dev
environment-defaults:
  graphql-dev:
    branch: null
    repository: null
global:
  application_name: graphql
  branch: main
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
