"""add more features for country

Revision ID: 85ea0de1116b
Revises: 56931f818b95
Create Date: 2023-12-21 15:21:32.776594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85ea0de1116b'
down_revision: Union[str, None] = '56931f818b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('culturetip', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('localcustom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'localcustom')
    op.drop_column('countries', 'culturetip')
    op.create_table('posts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.create_index('ix_posts_name', 'posts', ['name'], unique=False)
    op.create_index('ix_posts_content', 'posts', ['content'], unique=False)
    # ### end Alembic commands ###
