name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: List directory contents
      run: |
        ls -al

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install AWS Elastic Beanstalk CLI
      run: |
        pip install awsebcli

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        eb deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
